<Project>
    <Import Project="$(MSBuildThisFileDirectory)build\AssetPaths.props"/>
    <Import Project="$(MSBuildThisFileDirectory)build\CsharpLanguageSettings.props"/>
    <Import Project="$(MSBuildThisFileDirectory)build\PackageMetadata.props"/>
    <Import Project="$(MSBuildThisFileDirectory)build\PlatformSettings.props"/>
</Project>